# ================================================================
# BB2T1CE Diffusion Config
# ================================================================

exp_name: "BB2T1CE_localtest"
log_dir: "/workspace/nas100/forGPU2/Kimjihoo/ASAN_02_BB_T1CE/logs"
ckpt_dir: "/workspace/nas100/forGPU2/Kimjihoo/ASAN_02_BB_T1CE/logs/checkpoints"

data:
  root_dir: "/workspace/nas100/forGPU2/Kimjihoo/ASAN_02_BB_T1CE/data/0_RAW_DATA"
  n_slices_per_vol: 4
  batch_size: 2
  num_workers: 2
  image_size: 256            # ✅ 추가 (모델 입력 해상도)

model:
  ema_rate: 0.999
  type: simple
  ch: 64
  out_ch: 1
  ch_mult: [1, 2, 4, 8]
  num_res_blocks: 2
  dropout: 0.1
  attn_resolutions: [16]     # ✅ Attention 적용 해상도
  in_channels: 2             # ✅ 입력 채널 수 (BB + T1CE)
  resamp_with_conv: True     # ✅ Conv 기반 업/다운샘플링

diffusion:
  beta_schedule: "linear"
  beta_start: 0.0001
  beta_end: 0.02
  num_diffusion_timesteps: 1000

optim:
  lr: 1e-4
  grad_clip: 1.0

training:
  epochs: 10
  print_freq: 1
