# ================================================================
# model_unet.yml
# BB → T1CE Diffusion U-Net 모델 구성
# ================================================================

model:
  type: "custom"               # "custom" or "monai" (선택 가능)
  in_channels: 1               # 입력 채널 (noisy T1CE)
  cond_channels: 1             # 조건 채널 (BB sequence)
  out_channels: 1              # 출력 채널 (예측 노이즈)
  base_channels: 128           # 기본 feature 채널 수
  ch_mult: [1, 2, 4]           # 각 단계별 채널 배수
  num_res_blocks: 2            # ResNet block 개수
  dropout: 0.1                 # Dropout 비율
  attn_res: [16]               # Attention 추가할 해상도
