# ================================================================
# test_bb2t1ce.yml
# BB → T1CE Diffusion Inference 설정
# ================================================================

data:
  bb_dir: "/workspace/nas100/forGPU2/Kimjihoo/ASAN_02_BB_T1CE/data/0_RAW_DATA/meta-bb"
  save_dir: "./outputs/test"
  image_size: [256, 256]
  resample_spacing: [1.0, 1.0, 1.0]

model:
  type: "custom"
  ckpt_path: "./logs/checkpoints/ckpt_epoch100.pth"
  in_channels: 1
  cond_channels: 1
  out_channels: 1
  base_channels: 128
  ch_mult: [1, 2, 4]
  num_res_blocks: 2
  dropout: 0.1
  attn_res: [16]

diffusion:
  timesteps: 1000
  beta_start: 1e-4
  beta_end: 2e-2
